name: why_taxi_user
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.1+8

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dotted_border: ^2.0.0+2
  sizer: ^2.0.15
  http_parser: ^4.0.0
  font_awesome_flutter: ^9.2.0
  animated_widgets: ^1.1.0
  page_transition: ^2.0.4
  http: ^1.1.0
  fluttertoast: ^8.0.8
  cupertino_icons: ^1.0.3
  flutter_bloc: ^7.0.0
  shared_preferences: ^2.0.5
  #animation_wrappers: 0.0.2
  location: ^5.0.3
  intl:
 # geocoder: ^0.2.1
  geocoding: ^2.2.0
  google_maps_place_picker_mb: ^3.1.2
  google_maps_flutter: ^2.0.6
  flutter_polyline_points: ^2.0.0
  google_mobile_ads: ^0.13.2
  equatable: ^2.0.3
  image_picker_gallery_camera: ^0.2.2
  connectivity_plus: ^5.0.2
  flutter_html: 3.0.0-beta.2
  flutter_local_notifications: ^9.0.0
  path_provider: ^2.0.2
  permission_handler: ^10.2.0
  khalti_flutter: ^3.0.0
  firebase_auth: ^4.4.1
  social_share: ^2.2.1
  url_launcher: ^6.0.17
  flutter_datetime_picker_plus: ^2.0.1
 # flutter_datetime_picker: ^1.5.1
  flutter_branch_sdk: ^7.0.4
  google_sign_in: ^5.2.3
  flutter_login_facebook: ^1.4.1
  flutter_facebook_auth: ^4.3.0
  flutter_rating_bar: ^4.0.0
  firebase_core: ^2.9.0
  firebase_messaging: ^14.4.0
  firebase_dynamic_links: ^5.1.0
  animated_text_kit: ^4.2.2
  razorpay_flutter: ^1.2.9
 # screen: ^0.0.5
  wakelock_plus: ^1.1.4
  image_cropper: ^1.4.1
  device_info_plus: ^9.1.2
  #firebase_dynamic_links: ^5.1.0
dev_dependencies:
  flutter_test:
    sdk: flutter
#  flutter_launcher_icons: "^0.9.0"
dependency_overrides:
  file: ^6.1.4
  geolocator: ^9.0.2
#flutter_icons:
#  android: "ic_launcher"
#  ios: true
#  image_path: "assets/app_icons.png"

flutter_launcher_name:
  name: "Delris Cab"


flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/cars/
    - assets/users/
    - lib/language/
    - assets/fonts/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/inter.ttf

    - family: Olden
      fonts:
        - asset: assets/fonts/olden.ttf
    - family: Caveat
      fonts:
        - asset: assets/fonts/caveat.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/roboto.ttf